apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./argocd-monorepo-controller
- ./argocd-monorepo-repo-server
- ./config
images:
- name: quay.io/argoprojlabs/argocd-monorepo-controller
  newName: quay.io/argoprojlabs/argocd-monorepo-controller
  newTag: v0.0.4-rc3
