extra_css:
- assets/versions.css
- assets/extra.css
extra_javascript:
- assets/versions.js
markdown_extensions:
- markdown_include.include
- codehilite:
    css_class: highlight
- admonition
- toc:
    permalink: true
- pymdownx.superfences
nav:
- Overview: index.md
- Terminology: terminology.md
- Architecture: architecture.md
- Installation: install.md
- Helm Chart: helm.md
- Configuration Reference:
    - "Monorepo Controller Configuration": monorepo_controller_conf.md
    - "Monorepo Repo Server Configuration": monorepo_repo_server_conf.md
- Notifications: notifications.md
- Acknowledgements: acknowledgements.md
  
- Releases ⧉: https://github.com/argoproj-labs/argocd-monorepo-controller/releases
- Milestones ⧉: https://github.com/argoproj-labs/argocd-monorepo-controller/milestones

repo_url: https://github.com/argoproj-labs/argocd-monorepo-controller
site_name: Argo CD Monorepo Controller
site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true
theme:
  custom_dir: overrides
  favicon: assets/favicon.png
# false disables external links to downlad TTF fonts from internet
  font: false
#    text: Work Sans
  logo: assets/logo.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
